[package]
name = "photojawn"
version = "0.2.0"
description = "A static site generator for photo albums"
authors = ["Nick Pegg <nick@nickpegg.com>"]
license = "MIT"
repository = "https://github.com/nickpegg/photojawn"
edition = "2024"

[dependencies]
anyhow = "^1.0"
clap = { version = "^4.5", features = ["derive"] }
thiserror = "^2.0"

[dev-dependencies]
mktemp = "^0.5.1"
